### ISSUE TITLE
Cannot install in Windows

### ISSUE THREAD

**Issue by Ijoanito** [theislab/anndata2ri#21]
Hi, I am trying to install anndata2ri in Windows but it show errors as below:

<details>

```pytb
 ERROR: Complete output from command 'C:\Users\irwanij\anaconda3\python.exe' 'C:\Users\irwanij\anaconda3\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\irwanij\AppData\Local\Temp\pip-build-env-yaty7ttg\normal' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'pytest; extra == "test"' 'rpy2 >= 3.0.0.dev' anndata tzlocal 'pytest-faulthandler; extra == "test"':
  ERROR: Ignoring pytest: markers 'extra == "test"' don't match your environment
  Ignoring pytest-faulthandler: markers 'extra == "test"' don't match your environment
  Collecting rpy2>=3.0.0.dev
    Using cached https://files.pythonhosted.org/packages/c7/43/401afad8556bf92b08bd7d422cacac614b0e8dd2bce31848318bbcb18f48/rpy2-3.0.5.tar.gz
      ERROR: Complete output from command python setup.py egg_info:
      ERROR: Traceback (most recent call last):
        File "C:\Users\irwanij\anaconda3\lib\site-packages\cffi\cparser.py", line 294, in _parse
          ast = _get_parser().parse(fullcsource)
        File "C:\Users\irwanij\anaconda3\lib\site-packages\pycparser\c_parser.py", line 152, in parse
          debug=debuglevel)
        File "C:\Users\irwanij\anaconda3\lib\site-packages\pycparser\ply\yacc.py", line 331, in parse
          return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
        File "C:\Users\irwanij\anaconda3\lib\site-packages\pycparser\ply\yacc.py", line 1199, in parseopt_notrack
          tok = call_errorfunc(self.errorfunc, errtoken, self)
        File "C:\Users\irwanij\anaconda3\lib\site-packages\pycparser\ply\yacc.py", line 193, in call_errorfunc
          r = errorfunc(token)
        File "C:\Users\irwanij\anaconda3\lib\site-packages\pycparser\c_parser.py", line 1848, in p_error
          column=self.clex.find_tok_column(p)))
        File "C:\Users\irwanij\anaconda3\lib\site-packages\pycparser\plyparser.py", line 67, in _parse_error
          raise ParseError("%s: %s" % (coord, msg))
      pycparser.plyparser.ParseError: <cdef source string>:23:5: before: blah1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "C:\Users\irwanij\AppData\Local\Temp\pip-install-_g6dnslb\rpy2\setup.py", line 184, in <module>
          'rpy2': ['doc/source/rpy2_logo.png', ]}
        File "C:\Users\irwanij\anaconda3\lib\site-packages\setuptools\__init__.py", line 145, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\irwanij\anaconda3\lib\distutils\core.py", line 108, in setup
          _setup_distribution = dist = klass(attrs)
        File "C:\Users\irwanij\anaconda3\lib\site-packages\setuptools\dist.py", line 444, in __init__
          k: v for k, v in attrs.items()
        File "C:\Users\irwanij\anaconda3\lib\distutils\dist.py", line 292, in __init__
          self.finalize_options()
        File "C:\Users\irwanij\anaconda3\lib\site-packages\setuptools\dist.py", line 732, in finalize_options
          ep.load()(self, ep.name, value)
        File "C:\Users\irwanij\anaconda3\lib\site-packages\cffi\setuptools_ext.py", line 217, in cffi_modules
          add_cffi_module(dist, cffi_module)
        File "C:\Users\irwanij\anaconda3\lib\site-packages\cffi\setuptools_ext.py", line 49, in add_cffi_module
          execfile(build_file_name, mod_vars)
        File "C:\Users\irwanij\anaconda3\lib\site-packages\cffi\setuptools_ext.py", line 25, in execfile
          exec(code, glob, glob)
        File "rpy/_rinterface_cffi_build.py", line 546, in <module>
          """ if os.name == 'nt' else ''
        File "C:\Users\irwanij\anaconda3\lib\site-packages\cffi\api.py", line 112, in cdef
          self._cdef(csource, override=override, packed=packed, pack=pack)
        File "C:\Users\irwanij\anaconda3\lib\site-packages\cffi\api.py", line 126, in _cdef
          self._parser.parse(csource, override=override, **options)
        File "C:\Users\irwanij\anaconda3\lib\site-packages\cffi\cparser.py", line 347, in parse
          self._internal_parse(csource)
        File "C:\Users\irwanij\anaconda3\lib\site-packages\cffi\cparser.py", line 352, in _internal_parse
          ast, macros, csource = self._parse(csource)
        File "C:\Users\irwanij\anaconda3\lib\site-packages\cffi\cparser.py", line 296, in _parse
          self.convert_pycparser_error(e, csource)
        File "C:\Users\irwanij\anaconda3\lib\site-packages\cffi\cparser.py", line 325, in convert_pycparser_error
          raise CDefError(msg)
      cffi.CDefError: cannot parse "blah1 ReadConsole;"
      <cdef source string>:23:5: before: blah1
      ----------------------------------------
  ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\irwanij\AppData\Local\Temp\pip-install-_g6dnslb\rpy2\
  ----------------------------------------
ERROR: Command "'C:\Users\irwanij\anaconda3\python.exe' 'C:\Users\irwanij\anaconda3\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\irwanij\AppData\Local\Temp\pip-build-env-yaty7ttg\normal' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'pytest; extra == "test"' 'rpy2 >= 3.0.0.dev' anndata tzlocal 'pytest-faulthandler; extra == "test"'" failed with error code 1 in None
```

</details>

I have installed (hopefully) all requirement such as rpy2 version >= 3.0.0 (3.1.0.dev0), tzlocal (1.5.1), and anndata (0.6.22.post1). I am currently using anaconda with python version 3.7.3.

Can anyone help me with this problem?

**Comment by flying-sheep** [comment]
Hi! You apparently don’t have rpy2 installed, as your error occurs while pip tries to install rpy2. Consequently this isn’t a problem with anndata2ri.

While it tries to install rpy2, it seems to call the cffi package to parse [this header](https://github.com/s-u/Rserve/blob/8f72f2d7537b637980d4f3bcf8722f1b245f4046/src/include/Win32/Startup.h#L75) (which contains “blah1 ReadConsole”). No idea why. You should file this issue at the rpy2 repo.

**Comment by Ijoanito** [comment]
Thanks for your reply. 
actually I am running this comment to install anndata2ri:
'pip install git+https://github.com/flying-sheep/anndata2ri'

I already prepared all the dependency before hand. 
It is true that Installing rpy2 will have some issue. but I have manage to install it (either the 2.9.4 using anaconda or 3.1.0dev0 using pip). I have try to called rpy2 and it works.
for example, if I use the earlier version (2.9.4) and run this code:

import rpy2
print(rpy2.__version__)

import rpy2.situation
for row in rpy2.situation.iter_info():
    print(row)

I am getting:

2.9.4
Python version:
3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
Looking for R's HOME:
    Environment variable R_HOME: C:\Users\irwanij\anaconda3\Lib\R
    Calling `R RHOME`: C:\Users\irwanij\anaconda3\lib\R
    InstallPath in the registry: C:\Program Files\R\R-3.6.1
R version:
R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
https://www.gnu.org/licenses/.

    In the PATH: 
    Used to build rpy2: 3-6.0--76424
Additional directories to load R packages from:
None

However, when I try to install the anndata2ri, it again trying to install rpy2. That is why I am asking you regarding this problem. May I know whether your setup file will also install rpy2 automatically?

**Comment by flying-sheep** [comment]
I just specify rpy2 as a regular dependency. As you can see from your error output, the version anndata2ri needs is `rpy2>=3.0.0.dev`. You said you tried installing anndata2ri with `rpy2==3.1.0dev0` installed, that should have worked!

**Comment by flying-sheep** [comment]
The newest (or upcoming) version of rpy2 now has windows support
