### ISSUE TITLE
Fail to install on Windows

### ISSUE THREAD

**Issue by fkoegel** [theislab/anndata2ri#33]
Hello,
I'm trying to install anndata2ri, but I keep running into errors.
When I try to install through bioconda, I get some environment conflict (more on that in the text-file), any idea on as to why that would be?

<details><summary>Error</summary>

```
(sc-analysis-win) C:\Users\felix\Downloads>conda install anndata2ri
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.\
Examining r-blob:  90%|█████████████████████████████████████████████████████▊      | 383/427 [00:00<00:00, 3073.64it/s]\Examining r-r6:  98%|████████████████████████████████████████████████████████████▉ | 420/427 [00:00<00:00, 3073.64it/-
Comparing specs that have this dependency:   0%|                                                | 0/32 [00:00<?, ?it/\
/ mparing specs that have this dependency:  12%|█████                                   | 4/32 [00:01<00:08,  3.16it/\ \
Comparing specs that have this dependency:  34%|█████████████▍                         | 11/32 [00:05<00:10,  1.95it/s]|
Finding shortest conflict path for r-r6[version='>=2.2.2']:  25%|██████                  | 1/4 [00:03<00:10,  3.36s/i/ |
Finding shortest conflict path for r-r6:  50%|█████████████████████▌                     | 2/4 [00:03<00:03,  1.68s/i\ /
Comparing specs that have this dependency:  44%|█████████████████                      | 14/32 [00:14<00:18,  1.03s/i- \
Examining r-r6:  99%|█████████████████████████████████████████████████████████████▏| 421/427 [00:20<00:00, 3073.64it/\ |
Finding shortest conflict path for r-r6:  17%|███████▏                                   | 1/6 [00:00<00:04,  1.02it/| \
Comparing specs that have this dependency:  66%|█████████████████████████▌             | 21/32 [02:01<01:03,  5.79s/i/ |
failed                                                                                                                 /
                                                                                                                       -
UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package r-r6 conflicts for:
r-dbplyr -> r-r6[version='>=2.2.2']
r-callr -> r-r6
r-callr -> r-processx[version='>=3.1.0'] -> r-testthat -> r-r6[version='>=2.2.0']
r-purrr -> r-dplyr -> r-r6[version='>=2.2.2']
r-recommended -> mro-basics=3.5.1 -> r-r6[version='>=2.2.2,<2.2.3.0a0']
r-httr -> r-r6
r-progress -> r-r6
r-r6
r-promises -> r-r6
r-modelr -> r-dplyr -> r-r6[version='>=2.2.2']
r-shiny -> r-r6[version='>=2.0']
r-ggplot2 -> r-scales[version='>=0.4.1'] -> r-r6
r-tidyr -> r-dplyr[version='>=0.7.0'] -> r-r6[version='>=2.2.2']
r-rbokeh -> r-gistr -> r-dplyr -> r-r6[version='>=2.2.2']
r-reprex -> r-callr[version='>=2.0.0'] -> r-r6
r-recipes -> r-dplyr -> r-r6[version='>=2.2.2']
r-readr -> r-r6
r-scales -> r-r6
r-reprex -> r-callr[version='>=2.0.0'] -> r-processx[version='>=3.1.0'] -> r-testthat -> r-r6[version='>=2.2.0']
r-selectr -> r-r6
r-essentials -> r-recommended[version='>=3.6.0'] -> mro-basics=3.5.1 -> r-r6[version='>=2.2.2,<2.2.3.0a0']
r-caret -> r-recipes[version='>=0.0.1'] -> r-dplyr -> r-r6[version='>=2.2.2']
rpy2 -> r-dbplyr -> r-r6[version='>=2.2.2']
r-shiny -> r-httpuv[version='>=1.3.3'] -> r-r6
r-rbokeh -> r-r6
r-broom -> r-dplyr -> r-r6[version='>=2.2.2']
r-httpuv -> r-r6
r-tidyverse -> r-dbplyr[version='>=1.1.0'] -> r-r6[version='>=2.2.2']
r-essentials -> r-tidyverse[version='>=1.2.1'] -> r-reprex[version='>=0.1.1'] -> r-callr[version='>=2.0.0'] -> r-processx[version='>=3.1.0'] -> r-testthat -> r-r6[version='>=2.2.0']
r-processx -> r-r6
r-tidyverse -> r-reprex[version='>=0.1.1'] -> r-callr[version='>=2.0.0'] -> r-processx[version='>=3.1.0'] -> r-testthat -> r-r6[version='>=2.2.0']
r-processx -> r-testthat -> r-r6[version='>=2.2.0']
r-haven -> r-readr[version='>=0.1.0'] -> r-r6
r-pbdzmq -> r-r6
r-readxl -> r-progress -> r-r6
r-essentials -> r-dplyr[version='>=0.7.6'] -> r-r6[version='>=2.0|>=2.2.2']
r-rvest -> r-httr[version='>=0.5'] -> r-r6
r-dplyr -> r-r6[version='>=2.2.2']
r-irkernel -> r-pbdzmq[version='>=0.2_1'] -> r-r6
r-tidyselect -> r-purrr -> r-dplyr -> r-r6[version='>=2.2.2']
Note that strict channel priority may have removed packages required for satisfiability.
```

</details>

When I try to install through pip, I get an error message, it seems to be a problem with rpy2, but I don't exactly know what:

```bash
(sc-analysis-win) C:\Users\felix\Downloads>pip install anndata2ri
Collecting anndata2ri
  Using cached https://files.pythonhosted.org/packages/b7/09/34c48ce5b4e99d022dcde7e1643f4a9c1523fc91bb916b1c97891bdbdadd/anndata2ri-1.0-py3-none-any.whl
Requirement already satisfied: anndata in c:\programdata\anaconda3\envs\sc-analysis-win\lib\site-packages (from anndata2ri) (0.6.22.post1)
Collecting rpy2>=3.0.1 (from anndata2ri)
  Using cached https://files.pythonhosted.org/packages/7e/e0/7da849bb6cf47466ceb28a75f930e61c311878882c275dfb4bbb4fdcc3cb/rpy2-3.2.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\envs\sc-analysis-win\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\felix\\AppData\\Local\\Temp\\pip-install-0z14nnlr\\rpy2\\setup.py'"'"'; __file__='"'"'C:\\Users\\felix\\AppData\\Local\\Temp\\pip-install-0z14nnlr\\rpy2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\felix\AppData\Local\Temp\pip-install-0z14nnlr\rpy2\
    Complete output (17 lines):
    Der Befehl "sh" ist entweder falsch geschrieben oder
    konnte nicht gefunden werden.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\felix\AppData\Local\Temp\pip-install-0z14nnlr\rpy2\setup.py", line 102, in <module>
        c_extension_status = get_r_c_extension_status()
      File "C:\Users\felix\AppData\Local\Temp\pip-install-0z14nnlr\rpy2\setup.py", line 91, in get_r_c_extension_status
        *situation.get_r_flags(r_home, '--ldflags')
      File "C:\Users\felix\AppData\Local\Temp\pip-install-0z14nnlr\rpy2\rpy2\situation.py", line 176, in get_r_flags
        allow_empty=False)))
      File "C:\Users\felix\AppData\Local\Temp\pip-install-0z14nnlr\rpy2\rpy2\situation.py", line 145, in _get_r_cmd_config
        universal_newlines=True
      File "C:\ProgramData\Anaconda3\envs\sc-analysis-win\lib\subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "C:\ProgramData\Anaconda3\envs\sc-analysis-win\lib\subprocess.py", line 487, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '('C:\\ProgramData\\Anaconda3\\envs\\sc-analysis-win\\lib\\R\\bin\\x64\\R', 'CMD', 'config', '--ldflags')' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
``` 

I'm sorry, but some of the error is in German (I guess due to my system language), it just means:
The command 'sh' is either misspelled or does not exist.

I'm running Windows 10 64-bit with Anaconda.

Thank you very much already!

Regards, Felix.

**Comment by flying-sheep** [comment]
As you can see from the log, the error happens when trying to install the rpy2 dependency, not anndata2ri. Please search their issues and file a new one if you can’t find anyone with the same problem: https://bitbucket.org/rpy2/rpy2/issues

**Comment by flying-sheep** [comment]
The newest or upcoming version of rpy2 supports windows (It’s also hosted on GitHub now)
