### ISSUE TITLE
RuntimeError: found a situation in which we try to build a type recursively

### ISSUE THREAD

**Issue by Yujing-Bio** [theislab/anndata2ri#34]
Hi,

I am having trouble installing anndata2ri.

I tried:

```
pip install git+https://github.com/flying-sheep/anndata2ri.git
```

and `pip` / `flit install` locally.

I get same error message for all those methods:

```
RuntimeError: found a situation in which we try to build a type recursively.
This is known to occur e.g. in ``struct s { void(*callable)(struct s); }''.
Please report if you get this error and really need support for your case.
```

<details><summary>Traceback</summary>

```pytb
error.txt
(sc-tutorial) [ec2-user@ip-172-31-7-250 anndata2ri]$ pip install .
Processing /home/ec2-user/anaconda3/envs/sc-tutorial/bin/anndata2ri
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /home/ec2-user/anaconda3/envs/sc-tutorial/bin/python /home/ec2-user/anaconda3/envs/sc-tutorial/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpjfckxtk2
         cwd: /tmp/pip-req-build-4ltzomwp
    Complete output (35 lines):
    The file description seems not to be valid rst for PyPI; it will be interpreted as plain text
    <string>:30: (WARNING/2) 
    Cannot analyze code. Pygments package not found.

    Traceback (most recent call last):
      File "/home/ec2-user/anaconda3/envs/sc-tutorial/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
        main()
      File "/home/ec2-user/anaconda3/envs/sc-tutorial/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/ec2-user/anaconda3/envs/sc-tutorial/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 110, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-2pshb96a/overlay/lib/python3.7/site-packages/flit/buildapi.py", line 27, in prepare_metadata_for_build_wheel
        metadata = make_metadata(module, ini_info)
      File "/tmp/pip-build-env-2pshb96a/overlay/lib/python3.7/site-packages/flit/common.py", line 302, in make_metadata
        md_dict.update(get_info_from_module(module))
      File "/tmp/pip-build-env-2pshb96a/overlay/lib/python3.7/site-packages/flit/common.py", line 113, in get_info_from_module
        docstring, version = get_docstring_and_version_via_import(target)
      File "/tmp/pip-build-env-2pshb96a/overlay/lib/python3.7/site-packages/flit/common.py", line 97, in get_docstring_and_version_via_import
        m = sl.load_module()
      File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
      File "<frozen importlib._bootstrap_external>", line 907, in load_module
      File "<frozen importlib._bootstrap_external>", line 732, in load_module
      File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
      File "<frozen importlib._bootstrap>", line 696, in _load
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/pip-req-build-4ltzomwp/anndata2ri/__init__.py", line 10, in <module>
        from rpy2.rinterface import Sexp
      File "/tmp/pip-build-env-2pshb96a/normal/lib/python3.7/site-packages/rpy2/rinterface.py", line 6, in <module>
        from rpy2.rinterface_lib import openrlib
      File "/tmp/pip-build-env-2pshb96a/normal/lib/python3.7/site-packages/rpy2/rinterface_lib/openrlib.py", line 65, in <module>
        _get_dataptr_fallback)
      File "/tmp/pip-build-env-2pshb96a/normal/lib/python3.7/site-packages/rpy2/rinterface_lib/openrlib.py", line 50, in _get_symbol_or_fallback
        res = getattr(rlib, symbol)
    RuntimeError: found a situation in which we try to build a type recursively.  This is known to occur e.g. in ``struct s { void(*callable)(struct s); }''.  Please report if you get this error and really need support for your case.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ec2-user/anaconda3/envs/sc-tutorial/bin/python /home/ec2-user/anaconda3/envs/sc-tutorial/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpjfckxtk2 Check the logs for full command output.
```

</details>

####### Computer environment#################
aws centos 7 server
anaconda installed rgy2
Python 3.7.3
pip 19.3
Flit 1.3

**Comment by flying-sheep** [comment]
The error occurs in the `anndata2ri` line `from rpy2.rinterface import Sexp`, so it’s a rpy2 bug, not mine. Please report it there: https://bitbucket.org/rpy2/rpy2
