### ISSUE TITLE
Exception with huge sparse matrices

### ISSUE THREAD

**Issue by gokceneraslan** [theislab/anndata2ri#38]
I'm pretty sure this will be closed very quickly, but just wanted to write it here so that other people can benefit from it :)

When I try to convert a huge sparse matrix (like 1.3 million neurons dataset from 10X) to a sparse matrix in R, I get the following exception:

```pytb
  File "script.py", line 98, in main
    mat = anndata2ri.scipy2ri.py2rpy(sp.csr_matrix(mat))
  File "/opt/conda/lib/python3.7/site-packages/anndata2ri/scipy2ri/__init__.py", line 65, in py2rpy
    return converter.py2rpy(obj)
  File "/opt/conda/lib/python3.7/functools.py", line 827, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/opt/conda/lib/python3.7/site-packages/anndata2ri/scipy2ri/py2r.py", line 42, in wrapper
    return f(obj)
  File "/opt/conda/lib/python3.7/site-packages/anndata2ri/scipy2ri/py2r.py", line 66, in csr_to_rmat
    j=as_integer(csr.indices),
  File "/opt/conda/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 192, in __call__
    .__call__(*args, **kwargs))
  File "/opt/conda/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 113, in __call__
    new_args = [conversion.py2rpy(a) for a in args]
  File "/opt/conda/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 113, in <listcomp>
    new_args = [conversion.py2rpy(a) for a in args]
  File "/opt/conda/lib/python3.7/functools.py", line 827, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/opt/conda/lib/python3.7/site-packages/rpy2/robjects/numpy2ri.py", line 87, in numpy2rpy
    res = _numpyarray_to_r(o, _kinds[o.dtype.kind])
  File "/opt/conda/lib/python3.7/site-packages/rpy2/robjects/numpy2ri.py", line 60, in _numpyarray_to_r
    dim = ro.vectors.IntVector(a.shape)
  File "/opt/conda/lib/python3.7/site-packages/rpy2/robjects/vectors.py", line 413, in __init__
    super().__init__(obj)
  File "/opt/conda/lib/python3.7/site-packages/rpy2/rinterface_lib/sexp.py", line 288, in __init__
    super().__init__(type(self).from_object(obj).__sexp__)
  File "/opt/conda/lib/python3.7/site-packages/rpy2/rinterface_lib/sexp.py", line 372, in from_object
    res = cls.from_iterable(obj)
  File "/opt/conda/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py", line 28, in _
    cdata = function(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/rpy2/rinterface_lib/sexp.py", line 319, in from_iterable
    r_vector)
  File "/opt/conda/lib/python3.7/site-packages/rpy2/rinterface_lib/sexp.py", line 302, in _populate_r_vector
    cls._CAST_IN)
  File "/opt/conda/lib/python3.7/site-packages/rpy2/rinterface_lib/sexp.py", line 239, in _populate_r_vector
    set_elt(r_vector, i, cast_value(v))
OverflowError: integer 2253751917 does not fit 'int'
```

Matrix dimensions:

```
<1292537x22767 sparse matrix of type '<class 'numpy.float32'>'
        with 2623122961 stored elements in Compressed Sparse Row format>
```

So I wonder if there is an easy way to make this conversion work.

Currently R uses 32-bit integers with ±2147483647 limit, whereas in numpy default integers are 64bit.  sparse matrices in R are using 32-bit integer for offsets, so this seems infeasible.  One option might be to use double conversion, as suggested here, https://www.rdocumentation.org/packages/base/versions/3.6.1/topics/integer. But it won't solve the problem as sparse matrices probably cannot use double to index nonzeros in the matrix.

Edit: Or maybe it's doable with COO matrix format?

**Comment by flying-sheep** [comment]
Looks like a bug in `rpy2.robjects.numpy2ri`:

```py
import numpy as np
from rpy2.robjects import numpy2ri

arr = np.array([1, 2253751917], dtype=np.int64)
numpy2ri.py2rpy(arr)
# OverflowError: integer 2253751917 does not fit 'int'
```

interestingly, I also see:

```pytb
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/rpy2/rinterface_lib/sexp.py", line 369, in from_object
    res = cls.from_memoryview(mv)
  File "/usr/lib/python3.8/site-packages/rpy2/rinterface_lib/conversion.py", line 40, in _
    cdata = function(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/rpy2/rinterface_lib/sexp.py", line 346, in from_memoryview
    raise ValueError(msg)
ValueError: Incompatible C type sizes. The R array type is 4 bytes while the Python array type is 8 bytes.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  [your traceback]
```
